export default {
  login: "SAHARSH123",
  id: 30820624,
  node_id: "MDQ6VXNlcjMwODIwNjI0",
  avatar_url: "https://avatars.githubusercontent.com/u/30820624?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/SAHARSH123",
  html_url: "https://github.com/SAHARSH123",
  followers_url: "https://api.github.com/users/SAHARSH123/followers",
  following_url:
    "https://api.github.com/users/SAHARSH123/following{/other_user}",
  gists_url: "https://api.github.com/users/SAHARSH123/gists{/gist_id}",
  starred_url: "https://api.github.com/users/SAHARSH123/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/SAHARSH123/subscriptions",
  organizations_url: "https://api.github.com/users/SAHARSH123/orgs",
  repos_url: "https://api.github.com/users/SAHARSH123/repos",
  events_url: "https://api.github.com/users/SAHARSH123/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/SAHARSH123/received_events",
  type: "User",
  site_admin: false,
  name: "Saharsh Jain",
  company: null,
  blog: "saharshjain506@gmail.com",
  location: "Bengaluru",
  email: null,
  hireable: null,
  bio: "Software Engineer\r\nOracle India",
  twitter_username: null,
  public_repos: 43,
  public_gists: 6,
  followers: 4,
  following: 4,
  created_at: "2017-08-08T04:26:13Z",
  updated_at: "2023-02-18T09:09:46Z",
};
